services:
  # 대시보드 API 서비스
  dashboard-api:
    image: gmltn328/dashboard_api:latest
    container_name: scratcha_dashboard_api
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    command:
      [
        "uvicorn",
        "dashboard_api.app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
      ]

  # MySQL 데이터베이스 서비스
  db:
    image: mysql:8.0
    container_name: scratcha_db
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-time-zone=+00:00
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD",
        ]
      timeout: 20s
      retries: 10
      interval: 3s
      start_period: 30s
# Docker 볼륨 정의
volumes:
  db_data:
