services:
    scratcha_server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: scratcha_server
        env_file:
            - ./.env
        ports:
            - "8001:8001"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - ./app:/app/app
            - ./alembic:/app/alembic
            - ./alembic.ini:/app/alembic.ini
        depends_on:
            db:
                condition: service_healthy
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

    # MySQL 데이터베이스 서비스
    db:
        image: mysql:8.0
        container_name: scratcha_db
        env_file:
            - ./.env
        ports:
            - "3306:3306"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - scratcha_volume_local:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
            timeout: 20s
            retries: 10
            interval: 3s
            start_period: 30s
# Docker 볼륨 정의
volumes:
    scratcha_volume_local:
