"""Update column to usage_stats

Revision ID: 961198644cf7
Revises: ad03364769bb
Create Date: 2025-08-26 04:45:51.730738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '961198644cf7'
down_revision: Union[str, Sequence[str], None] = 'ad03364769bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('usage_stats', sa.Column('total_latency_ms', sa.Integer(), nullable=False, server_default='0', comment='총 지연 시간 (ms)'))
    # op.add_column('usage_stats', sa.Column('verification_count', sa.Integer(), nullable=False, server_default='0', comment='총 검증 횟수'))
    op.alter_column('usage_stats', 'captcha_timeout_count',
               existing_type=mysql.INTEGER(),
               comment='타임아웃 응답 수',
               existing_nullable=False)
    op.execute("UPDATE usage_stats SET avg_response_time_ms = 0.0 WHERE avg_response_time_ms IS NULL")
    op.alter_column('usage_stats', 'avg_response_time_ms',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False,
               server_default='0.0',
               comment='평균 응답 시간 (ms)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_stats', 'avg_response_time_ms',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True,
               comment=None,
               existing_comment='평균 응답 시간 (ms)')
    op.alter_column('usage_stats', 'captcha_timeout_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='타임아웃 응답 수',
               existing_nullable=False)
    op.drop_column('usage_stats', 'verification_count')
    op.drop_column('usage_stats', 'total_latency_ms')
    # ### end Alembic commands ###
