"""Add captchaTimeoutCount to usage_stats

Revision ID: ad03364769bb
Revises: cfb570fd4fd2
Create Date: 2025-08-26 01:27:47.333188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad03364769bb'
down_revision: Union[str, Sequence[str], None] = 'cfb570fd4fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_stats', 'captcha_fail_count',
               existing_type=mysql.INTEGER(),
               comment='실패 응답 수',
               existing_comment='성공 응답 수',
               existing_nullable=False)
    op.alter_column('usage_stats', 'captcha_timeout_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='타임아웃 응답 수')
    op.drop_column('usage_stats', 'avg_response_time_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_stats', sa.Column('avg_response_time_ms', mysql.DOUBLE(asdecimal=True), nullable=True))
    op.alter_column('usage_stats', 'captcha_timeout_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='타임아웃 응답 수')
    op.alter_column('usage_stats', 'captcha_fail_count',
               existing_type=mysql.INTEGER(),
               comment='성공 응답 수',
               existing_comment='실패 응답 수',
               existing_nullable=False)
    # ### end Alembic commands ###
