"""Modify app_api_ke, auth_users teble

Revision ID: ad87a758c014
Revises: 990942cacaf8
Create Date: 2025-08-05 08:12:37.374795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad87a758c014'
down_revision: Union[str, Sequence[str], None] = '990942cacaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_api_keys', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('auth_users', sa.Column('subscribe', sa.String(length=20), nullable=False))
    op.add_column('auth_users', sa.Column('token', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'token')
    op.drop_column('auth_users', 'subscribe')
    op.drop_column('app_api_keys', 'deleted_at')
    # ### end Alembic commands ###
