"""edit table: captcha_problem

Revision ID: b1213bf427fa
Revises: ec2b12294352
Create Date: 2025-08-13 02:49:55.947552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1213bf427fa'
down_revision: Union[str, Sequence[str], None] = 'ec2b12294352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captcha_problem', sa.Column('wrong_answer_1', sa.String(length=20), nullable=False, comment='오답1'))
    op.add_column('captcha_problem', sa.Column('wrong_answer_2', sa.String(length=20), nullable=False, comment='오답2'))
    op.add_column('captcha_problem', sa.Column('wrong_answer_3', sa.String(length=20), nullable=False, comment='오답3'))
    op.alter_column('captcha_problem', 'difficulty',
               existing_type=mysql.SMALLINT(),
               type_=sa.Integer(),
               existing_comment='문제 난이도',
               existing_nullable=False)
    op.drop_column('captcha_problem', 'worng_answer1')
    op.drop_column('captcha_problem', 'worng_answer2')
    op.drop_column('captcha_problem', 'worng_answer3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captcha_problem', sa.Column('worng_answer3', mysql.VARCHAR(length=20), nullable=False, comment='오답3'))
    op.add_column('captcha_problem', sa.Column('worng_answer2', mysql.VARCHAR(length=20), nullable=False, comment='오답2'))
    op.add_column('captcha_problem', sa.Column('worng_answer1', mysql.VARCHAR(length=20), nullable=False, comment='오답1'))
    op.alter_column('captcha_problem', 'difficulty',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(),
               existing_comment='문제 난이도',
               existing_nullable=False)
    op.drop_column('captcha_problem', 'wrong_answer_3')
    op.drop_column('captcha_problem', 'wrong_answer_2')
    op.drop_column('captcha_problem', 'wrong_answer_1')
    # ### end Alembic commands ###
