"""edit User Table

Revision ID: cc225e9fee11
Revises: cf001b721887
Create Date: 2025-08-05 01:19:59.953438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc225e9fee11'
down_revision: Union[str, Sequence[str], None] = 'cf001b721887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('auth_users', 'user_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('auth_users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'USER', name='userrole'),
               existing_nullable=False)
    op.alter_column('auth_users', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('auth_users', 'deleted_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('email', table_name='auth_users')
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.create_index('email', 'auth_users', ['email'], unique=True)
    op.alter_column('auth_users', 'deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('auth_users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('auth_users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('auth_users', 'user_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('auth_users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
