"""edit table: captcha_problem

Revision ID: ec2b12294352
Revises: c1e1391e28df
Create Date: 2025-08-13 02:33:21.217605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2b12294352'
down_revision: Union[str, Sequence[str], None] = 'c1e1391e28df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captcha_problem', sa.Column('difficulty', sa.SmallInteger(), nullable=False, comment='문제 난이도'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captcha_problem', 'difficulty')
    # ### end Alembic commands ###
