name: CI/CD Pipeline

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build-and-test:
        runs-on: self-hosted # <-- 이 부분을 self-hosted로 변경합니다.

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              run: docker-compose build

            - name: Run tests (if any)
              run: echo "No tests defined yet. Add your test commands here."

    deploy:
        needs: build-and-test
        runs-on: self-hosted # <-- 이 부분을 self-hosted로 변경합니다.
        if: github.ref == 'refs/heads/develop'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_IMAGE }}:latest

            - name: Set up SSH Agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to server via Bastion
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
                  BACKEND_HOST: ${{ secrets.BACKEND_HOST }}
                  BACKEND_USERNAME: ${{ secrets.BACKEND_USERNAME }}
                  REMOTE_APP_PATH: /home/ubuntu
              run: |
                  set -x

                  mkdir -p ~/.ssh
                  ssh-keyscan -v -H "$SSH_HOST" >> ~/.ssh/known_hosts
                  ssh-keyscan -v -H "$BACKEND_HOST" >> ~/.ssh/known_hosts

                  ssh -v -o StrictHostKeyChecking=no -o ProxyCommand="ssh -v -W %h:%p ${{ env.SSH_USERNAME }}@${{ env.SSH_HOST }}" "${{ env.BACKEND_USERNAME }}@${{ env.BACKEND_HOST }}" "docker stop scratcha_server || true && docker rm scratcha_server || true && docker pull ${{ secrets.DOCKER_IMAGE }}:latest && docker run -d --name scratcha_server --env-file /home/${{ env.BACKEND_USERNAME }}/.env -p 8001:8001 ${{ secrets.DOCKER_IMAGE }}:latest"
